### ISSUE TITLE
antd-form-schema-form: run error

### ISSUE THREAD

**Issue by ardorcheng** [drdevelop/antd-pro#1]
antd: v4
current version: 1.0.0-rc.3
error msg: Cannot add property current, object is not extensible useImperativeHandle

**Comment by drdevelop** [comment]
Sorry, I forgot forwardRef when calling useImperativeHandle in the react hook component in this version, you can try to upgrade to 1.0.0-rc.7 or above.

**Comment by ardorcheng** [comment]
Yeap, the version 1.0.0-rc.7 run success. Thanks!
