### ISSUE TITLE
Schema type类型未导出

### ISSUE THREAD

**Issue by wulucxy** [drdevelop/antd-pro#43]

**Comment by drdevelop** [comment]
@wulucxy 是schema这个大类型还是schema里面的type内置组件枚举属性类型？

**Comment by wulucxy** [comment]
Schema 大类型未导出

**Comment by wulucxy** [comment]
另外请教一下，在现有 antd form 下嵌套会报warning，这个有好的解决办法么

![image](https://github.com/drdevelop/antd-pro/assets/5326403/7f66d3ec-389f-49a2-b524-e4356be05fd7)

**Comment by drdevelop** [comment]
@wulucxy 提供个最小复现demo？还没遇到过

**Comment by drdevelop** [comment]
@wulucxy 表单warning问题在这个issue跟进吧#44

**Comment by wulucxy** [comment]
没法迁移，本身 schemaForm 在当前业务场景下只是 Form 下面的一个 FormItem

**Comment by drdevelop** [comment]
@wulucxy ok，这个我看看怎么支持，应该是可以的

**Comment by drdevelop** [comment]
> 没法迁移，本身 schemaForm 在当前业务场景下只是 Form 下面的一个 FormItem

试试最新版本1.5.0支持了，注意传递hybrid: true属性开启新旧表单混合使用能力

**Comment by drdevelop** [comment]
> 没法迁移，本身 schemaForm 在当前业务场景下只是 Form 下面的一个 FormItem

@wulucxy 试试最新版本1.5.0支持了，注意传递hybrid: true属性开启新旧表单混合使用能力

**Comment by drdevelop** [comment]
> 没法迁移，本身 schemaForm 在当前业务场景下只是 Form 下面的一个 FormItem

试试最新版本1.5.0支持了，注意传递hybrid: true属性开启新旧表单混合使用能力，用法参考https://drdevelop.github.io/antd-pro/index.html#/schema-form/with-jsx

**Comment by drdevelop** [comment]
> 没法迁移，本身 schemaForm 在当前业务场景下只是 Form 下面的一个 FormItem

@wulucxy 试试最新版本1.5.0支持了，注意传递hybrid: true属性开启新旧表单混合使用能力，用法参考https://drdevelop.github.io/antd-pro/index.html#/schema-form/with-jsx

**Comment by drdevelop** [comment]
> @drdevelop Schema ts 类型要怎么获取，升级了以后还是找不到类型
> 
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/5326403/275368906-951cc590-761f-4444-a4fc-6d307fe95b1a.png">

@wulucxy 这个还没来得及处理，今天下班后晚上会发个版解决

**Comment by drdevelop** [comment]
@wulucxy 急的话可先用SchemaFormProps['schema']替代

**Comment by drdevelop** [comment]
> @drdevelop Schema ts 类型要怎么获取，升级了以后还是找不到类型
> 
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/5326403/275368906-951cc590-761f-4444-a4fc-6d307fe95b1a.png">

@wulucxy 1.5.1可以了

**Comment by wulucxy** [comment]
done

**Comment by wulucxy** [comment]
onValuesChange 是不是改没了 555
