### ISSUE TITLE
1.5.1 form onValuesChange 不可用

### ISSUE THREAD

**Issue by wulucxy** [drdevelop/antd-pro#47]

**Comment by drdevelop** [comment]
hybrid模式下不要传递onValuesChange给SchemaForm, 因为此时复用的是业务本身的Form，把onValuesChange传给原先业务中antd的Form就好了

**Comment by drdevelop** [comment]
![Screenshot_20231017_144023_com huawei browser_edit_711190219506062](https://github.com/drdevelop/antd-pro/assets/39514265/f1fe7306-8bba-41ed-9942-1561bbad271a)
@wulucxy

**Comment by wulucxy** [comment]
目前这个架构不太支持，SchemaForm 所在的区域作为一个插件嵌入，外层 Form 容器不感知，所以期望 hybrid 也提供 valuesChange 方法
![image](https://github.com/drdevelop/antd-pro/assets/5326403/7f946cf1-6e00-4ad9-a794-04cbb7e1bea2)

**Comment by drdevelop** [comment]
@wulucxy 找到方式了，晚上加下该功能

**Comment by drdevelop** [comment]
> 目前这个架构不太支持，SchemaForm 所在的区域作为一个插件嵌入，外层 Form 容器不感知，所以期望 hybrid 也提供 valuesChange 方法 ![image](https://user-images.githubusercontent.com/5326403/275735353-7f946cf1-6e00-4ad9-a794-04cbb7e1bea2.png)
> 
> @drdevelop

@wulucxy 试试1.5.2，注意SchemaForm只能监听其作用域下的表单项并回调onValuesChange

**Comment by wulucxy** [comment]
@drdevelop 可以用，不过有个小问题。

1.4 版本 onValuesChange 第一个参数就是 allValues，1.5 把 allValues 作为第二个参数了，低版本直接升级是否不兼容？

**Comment by drdevelop** [comment]
> @drdevelop 可以用，不过有个小问题。
> 
> 1.4 版本 onValuesChange 第一个参数就是 allValues，1.5 把 allValues 作为第二个参数了，低版本直接升级是否不兼容？

![Screenshot_20231018_094813_com huawei browser](https://github.com/drdevelop/antd-pro/assets/39514265/f1d48659-64fe-4786-9b23-4bd014fa9055)
这个参数的设计初衷是和官方的onValuesChange保持一致的 @wulucxy

**Comment by drdevelop** [comment]
@wulucxy 你好，1.4我这边试了下onValuesChange第一个参数接收到的对象里仅包含当前变更项表单的值，第二个才是allValues，没复现你说的情况，或者你可以提供下最小复现demo

**Comment by wulucxy** [comment]
> @wulucxy 你好，1.4我这边试了下onValuesChange第一个参数接收到的对象里仅包含当前变更项表单的值，第二个才是allValues，没复现你说的情况，或者你可以提供下最小复现demo

那可能是我用法错了，谢谢
